#!/bin/bash
# put this at the beginning of each of your scripts
# it will remove the centos7 repos, which are flakey right now
# and put in our (more stable) repositories.
apt install -y nfs-client
showmount -e 10.128.0.16
mkdir /mnt/test
echo "10.128.0.16:/var/nfsshare/testing     /mnt/test     nfs     defaults 0 0" >> /etc/fstab
mount -a
*profit*
